// This file is auto-generated by scripts/generate.ts. Do not edit manually.
export interface ProtoMethodRegistry {
  methodName: string;
  requestType: string;
  responseType: string;
  requestStream: boolean;
  responseStream: boolean;
  requestFieldCount: number;
  eventName: string;
}

export interface ProtoServiceRegistry {
  packageName: string;
  serviceName: string;
  fullServiceName: string;
  methods: readonly ProtoMethodRegistry[];
}

export const protoRegistry = {
  protoFiles: [
  "src/proto/dmr_classifier.proto",
  "src/proto/sdr.proto",
  "src/proto/signal_recorder.proto",
  "src/proto/tetra_classifier.proto"
],
  services: [
  {
    "packageName": "dmr_classifier.v1",
    "serviceName": "DMRClassifier",
    "fullServiceName": "dmr_classifier.v1.DMRClassifier",
    "methods": [
      {
        "methodName": "ClassifyFrequency",
        "requestType": "dmr_classifier.v1.ClassifyFrequencyRequest",
        "responseType": "dmr_classifier.v1.ClassifyFrequencyResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 5,
        "eventName": "DMRClassifier.ClassifyFrequency"
      }
    ]
  },
  {
    "packageName": "sdr_ingestion.v2",
    "serviceName": "DeviceControl",
    "fullServiceName": "sdr_ingestion.v2.DeviceControl",
    "methods": [
      {
        "methodName": "ListDevices",
        "requestType": "sdr_ingestion.v2.ListDevicesRequest",
        "responseType": "sdr_ingestion.v2.ListDevicesResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 0,
        "eventName": "DeviceControl.ListDevices"
      },
      {
        "methodName": "OpenDevice",
        "requestType": "sdr_ingestion.v2.OpenDeviceRequest",
        "responseType": "sdr_ingestion.v2.OpenDeviceResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 7,
        "eventName": "DeviceControl.OpenDevice"
      },
      {
        "methodName": "CloseDevice",
        "requestType": "sdr_ingestion.v2.CloseDeviceRequest",
        "responseType": "sdr_ingestion.v2.CloseDeviceResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 1,
        "eventName": "DeviceControl.CloseDevice"
      },
      {
        "methodName": "SetFrequency",
        "requestType": "sdr_ingestion.v2.SetFrequencyRequest",
        "responseType": "sdr_ingestion.v2.SetFrequencyResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 2,
        "eventName": "DeviceControl.SetFrequency"
      },
      {
        "methodName": "SetSampleRate",
        "requestType": "sdr_ingestion.v2.SetSampleRateRequest",
        "responseType": "sdr_ingestion.v2.SetSampleRateResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 2,
        "eventName": "DeviceControl.SetSampleRate"
      },
      {
        "methodName": "SetGain",
        "requestType": "sdr_ingestion.v2.SetGainRequest",
        "responseType": "sdr_ingestion.v2.SetGainResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 3,
        "eventName": "DeviceControl.SetGain"
      },
      {
        "methodName": "SetFrequencyCorrection",
        "requestType": "sdr_ingestion.v2.SetFreqCorrRequest",
        "responseType": "sdr_ingestion.v2.SetFreqCorrResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 2,
        "eventName": "DeviceControl.SetFrequencyCorrection"
      },
      {
        "methodName": "GetDeviceState",
        "requestType": "sdr_ingestion.v2.GetDeviceStateRequest",
        "responseType": "sdr_ingestion.v2.GetDeviceStateResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 1,
        "eventName": "DeviceControl.GetDeviceState"
      },
      {
        "methodName": "SetHarogicConfig",
        "requestType": "sdr_ingestion.v2.SetHarogicConfigRequest",
        "responseType": "sdr_ingestion.v2.SetHarogicConfigResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 2,
        "eventName": "DeviceControl.SetHarogicConfig"
      },
      {
        "methodName": "ListSessions",
        "requestType": "sdr_ingestion.v2.ListSessionsRequest",
        "responseType": "sdr_ingestion.v2.ListSessionsResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 0,
        "eventName": "DeviceControl.ListSessions"
      }
    ]
  },
  {
    "packageName": "sdr_ingestion.v2",
    "serviceName": "IQStream",
    "fullServiceName": "sdr_ingestion.v2.IQStream",
    "methods": [
      {
        "methodName": "Subscribe",
        "requestType": "sdr_ingestion.v2.SubscribeRequest",
        "responseType": "sdr_ingestion.v2.IQChunk",
        "requestStream": false,
        "responseStream": true,
        "requestFieldCount": 5,
        "eventName": "IQStream.Subscribe"
      }
    ]
  },
  {
    "packageName": "sdr_ingestion.v2",
    "serviceName": "SpectrumStream",
    "fullServiceName": "sdr_ingestion.v2.SpectrumStream",
    "methods": [
      {
        "methodName": "SubscribeRTSpectrum",
        "requestType": "sdr_ingestion.v2.SubscribeRTSpectrumRequest",
        "responseType": "sdr_ingestion.v2.SpectrumFrame",
        "requestStream": false,
        "responseStream": true,
        "requestFieldCount": 2,
        "eventName": "SpectrumStream.SubscribeRTSpectrum"
      },
      {
        "methodName": "SubscribeWaterfall",
        "requestType": "sdr_ingestion.v2.SubscribeWaterfallRequest",
        "responseType": "sdr_ingestion.v2.WaterfallTile",
        "requestStream": false,
        "responseStream": true,
        "requestFieldCount": 2,
        "eventName": "SpectrumStream.SubscribeWaterfall"
      },
      {
        "methodName": "SubscribeSweep",
        "requestType": "sdr_ingestion.v2.SubscribeSweepRequest",
        "responseType": "sdr_ingestion.v2.SweepTrace",
        "requestStream": false,
        "responseStream": true,
        "requestFieldCount": 4,
        "eventName": "SpectrumStream.SubscribeSweep"
      }
    ]
  },
  {
    "packageName": "signal_recorder.v1",
    "serviceName": "SignalRecorder",
    "fullServiceName": "signal_recorder.v1.SignalRecorder",
    "methods": [
      {
        "methodName": "StartRecording",
        "requestType": "signal_recorder.v1.StartRecordingRequest",
        "responseType": "signal_recorder.v1.StartRecordingResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 10,
        "eventName": "SignalRecorder.StartRecording"
      },
      {
        "methodName": "StopRecording",
        "requestType": "signal_recorder.v1.StopRecordingRequest",
        "responseType": "signal_recorder.v1.StopRecordingResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 1,
        "eventName": "SignalRecorder.StopRecording"
      },
      {
        "methodName": "GetRecording",
        "requestType": "signal_recorder.v1.GetRecordingRequest",
        "responseType": "signal_recorder.v1.GetRecordingResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 1,
        "eventName": "SignalRecorder.GetRecording"
      },
      {
        "methodName": "ListRecordings",
        "requestType": "signal_recorder.v1.ListRecordingsRequest",
        "responseType": "signal_recorder.v1.ListRecordingsResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 3,
        "eventName": "SignalRecorder.ListRecordings"
      },
      {
        "methodName": "DeleteRecording",
        "requestType": "signal_recorder.v1.DeleteRecordingRequest",
        "responseType": "signal_recorder.v1.DeleteRecordingResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 2,
        "eventName": "SignalRecorder.DeleteRecording"
      },
      {
        "methodName": "WatchRecording",
        "requestType": "signal_recorder.v1.WatchRecordingRequest",
        "responseType": "signal_recorder.v1.RecordingEvent",
        "requestStream": false,
        "responseStream": true,
        "requestFieldCount": 1,
        "eventName": "SignalRecorder.WatchRecording"
      }
    ]
  },
  {
    "packageName": "tetra_classifier.v1",
    "serviceName": "TETRAClassifier",
    "fullServiceName": "tetra_classifier.v1.TETRAClassifier",
    "methods": [
      {
        "methodName": "ClassifyFrequency",
        "requestType": "tetra_classifier.v1.ClassifyFrequencyRequest",
        "responseType": "tetra_classifier.v1.ClassifyFrequencyResponse",
        "requestStream": false,
        "responseStream": false,
        "requestFieldCount": 7,
        "eventName": "TETRAClassifier.ClassifyFrequency"
      }
    ]
  }
],
  eventNames: [
  "DMRClassifier.ClassifyFrequency",
  "DeviceControl.ListDevices",
  "DeviceControl.OpenDevice",
  "DeviceControl.CloseDevice",
  "DeviceControl.SetFrequency",
  "DeviceControl.SetSampleRate",
  "DeviceControl.SetGain",
  "DeviceControl.SetFrequencyCorrection",
  "DeviceControl.GetDeviceState",
  "DeviceControl.SetHarogicConfig",
  "DeviceControl.ListSessions",
  "IQStream.Subscribe",
  "SpectrumStream.SubscribeRTSpectrum",
  "SpectrumStream.SubscribeWaterfall",
  "SpectrumStream.SubscribeSweep",
  "SignalRecorder.StartRecording",
  "SignalRecorder.StopRecording",
  "SignalRecorder.GetRecording",
  "SignalRecorder.ListRecordings",
  "SignalRecorder.DeleteRecording",
  "SignalRecorder.WatchRecording",
  "TETRAClassifier.ClassifyFrequency"
]
} as const;
